linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - dupl
    - dupword
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - goconst
    - gocritic
    - godox
    - gomoddirectives
    - gosec
    - inamedparam
    - intrange
    - lll
    - mnd
    - musttag
    - paralleltest
    - perfsprint
    - recvcheck
    - revive
    - stylecheck
    - tagliatelle
    - tenv
    - testifylint
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
